package me.kzheart.klib.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.work.DisableCachingByDefault;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.Optional;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.Locale;
import java.util.regex.Pattern;

/**
 * 把 {@code klib { remote { } }} 的服务端地址、公开写入 Key 与能力上限生成为常量类。
 *
 * <p>生成的 Key 随插件 JAR 分发，只能提交事件与读取公开策略，不是秘密或安装身份证明。
 */
@DisableCachingByDefault(because = "Generated source contains an environment-specific public ingest key")
public abstract class GenerateRemoteAccessTask extends DefaultTask {
    /** 生成类的简单名，同时是文件名。 */
    public static final String CLASS_NAME = "KlibRemoteAccess";
    private static final Pattern PUBLIC_KEY =
            Pattern.compile("rpk_(live|test)_[A-Za-z0-9_-]{43}");

    @Input
    public abstract Property<Boolean> getRemoteConfigured();

    @Input
    @Optional
    public abstract Property<String> getEndpoint();

    @Input
    @Optional
    public abstract Property<String> getPublicKey();

    @Input
    public abstract Property<Boolean> getExceptionsEnabled();

    @Input
    public abstract Property<Boolean> getLogsEnabled();

    @Input
    public abstract Property<Boolean> getManualIncidentsEnabled();

    @Input
    @Optional
    public abstract Property<String> getMainClass();

    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    @TaskAction
    public void generate() {
        Path root = getOutputDirectory().get().getAsFile().toPath();
        clean(root);
        if (!Boolean.TRUE.equals(getRemoteConfigured().getOrElse(Boolean.FALSE))) {
            return;
        }
        String endpoint = endpoint(getEndpoint().getOrElse(""));
        String publicKey = publicKey(getPublicKey().getOrElse(""));
        boolean exceptionsEnabled = getExceptionsEnabled().getOrElse(Boolean.FALSE);
        boolean logsEnabled = getLogsEnabled().getOrElse(Boolean.FALSE);
        boolean manualIncidentsEnabled =
                getManualIncidentsEnabled().getOrElse(Boolean.FALSE);
        String packageName = packageOf(getMainClass().getOrElse(""));

        Path directory = root;
        for (String part : packageName.split("\\.")) {
            directory = directory.resolve(part);
        }
        Path source = directory.resolve(CLASS_NAME + ".java");
        try {
            Files.createDirectories(directory);
            Files.write(
                    source,
                    render(packageName, endpoint, publicKey, exceptionsEnabled, logsEnabled,
                            manualIncidentsEnabled)
                            .getBytes(StandardCharsets.UTF_8));
        } catch (IOException failure) {
            throw new GradleException("Cannot write generated " + CLASS_NAME + ".java", failure);
        }
    }

    private static String render(
            String packageName,
            String endpoint,
            String publicKey,
            boolean exceptionsEnabled,
            boolean logsEnabled,
            boolean manualIncidentsEnabled
    ) {
        StringBuilder java = new StringBuilder();
        java.append("package ").append(packageName).append(";\n\n");
        java.append("/**\n");
        java.append(" * Generated by the klib Gradle plugin. DO NOT EDIT.\n");
        java.append(" *\n");
        java.append(" * <p>The ingest key is public and ships inside the plugin jar.\n");
        java.append(" */\n");
        java.append("public final class ").append(CLASS_NAME).append(" {\n");
        java.append("    /** Remote service base URL. */\n");
        java.append("    public static final String ENDPOINT = \"")
                .append(escape(endpoint)).append("\";\n\n");
        java.append("    /** Public, write-only Remote project key. */\n");
        java.append("    public static final String PUBLIC_KEY = \"")
                .append(escape(publicKey)).append("\";\n\n");
        java.append("    /** Build-time ceiling for automatic exception incidents. */\n");
        java.append("    public static final boolean EXCEPTIONS_ENABLED = ")
                .append(exceptionsEnabled).append(";\n\n");
        java.append("    /** Build-time ceiling for continuous plugin log delivery. */\n");
        java.append("    public static final boolean LOGS_ENABLED = ")
                .append(logsEnabled).append(";\n\n");
        java.append("    /** Build-time ceiling for explicit manual incidents. */\n");
        java.append("    public static final boolean MANUAL_INCIDENTS_ENABLED = ")
                .append(manualIncidentsEnabled).append(";\n\n");
        java.append("    private ").append(CLASS_NAME).append("() {\n");
        java.append("    }\n");
        java.append("}\n");
        return java.toString();
    }

    private static String escape(String value) {
        StringBuilder escaped = new StringBuilder(value.length() + 8);
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\':
                    escaped.append("\\\\");
                    break;
                case '"':
                    escaped.append("\\\"");
                    break;
                case '\n':
                    escaped.append("\\n");
                    break;
                case '\r':
                    escaped.append("\\r");
                    break;
                case '\t':
                    escaped.append("\\t");
                    break;
                default:
                    if (character < 0x20 || character == 0x7f) {
                        escaped.append(String.format("\\u%04x", (int) character));
                    } else {
                        escaped.append(character);
                    }
            }
        }
        return escaped.toString();
    }

    private static String endpoint(String value) {
        String endpoint = require("remote.endpoint", value);
        URI uri;
        try {
            uri = new URI(endpoint);
        } catch (URISyntaxException malformed) {
            throw new GradleException("klib.remote.endpoint is not a valid URL", malformed);
        }
        String scheme = uri.getScheme() == null ? "" : uri.getScheme().toLowerCase(Locale.ROOT);
        if (!"https".equals(scheme)) {
            throw new GradleException("klib.remote.endpoint must use https");
        }
        if (uri.getHost() == null || uri.getHost().isEmpty()) {
            throw new GradleException("klib.remote.endpoint must contain a host");
        }
        if (uri.getRawUserInfo() != null || uri.getRawQuery() != null
                || uri.getRawFragment() != null) {
            throw new GradleException(
                    "klib.remote.endpoint contains forbidden components");
        }
        return endpoint;
    }

    private static String packageOf(String mainClass) {
        String main = MainClassSpec.require(mainClass);
        return main.substring(0, main.lastIndexOf('.'));
    }

    private static String publicKey(String value) {
        String key = require("remote.publicKey", value);
        if (!PUBLIC_KEY.matcher(key).matches()) {
            throw new GradleException(
                    "klib.remote.publicKey must be a public rpk_live_ or rpk_test_ Remote key");
        }
        return key;
    }

    private static String require(String field, String value) {
        if (value == null || value.trim().isEmpty()) {
            throw new GradleException("klib." + field + " must not be blank");
        }
        return value.trim();
    }

    private static void clean(Path root) {
        if (!Files.isDirectory(root)) {
            return;
        }
        try {
            Files.walkFileTree(root, new SimpleFileVisitor<Path>() {
                @Override
                public FileVisitResult visitFile(Path file, BasicFileAttributes attributes)
                        throws IOException {
                    Files.delete(file);
                    return FileVisitResult.CONTINUE;
                }

                @Override
                public FileVisitResult postVisitDirectory(Path directory, IOException failure)
                        throws IOException {
                    if (failure != null) {
                        throw failure;
                    }
                    if (!directory.equals(root)) {
                        Files.delete(directory);
                    }
                    return FileVisitResult.CONTINUE;
                }
            });
        } catch (IOException failure) {
            throw new GradleException("Cannot clean generated remote access sources", failure);
        }
    }
}
